"""empty message

Revision ID: 2b2011816714
Revises: None
Create Date: 2015-10-18 02:20:41.568000

"""

# revision identifiers, used by Alembic.
revision = '2b2011816714'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat')
    ### end Alembic commands ###
